version = 1

test_patterns = ["tests/**"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 100

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
